name: iOS Build & Test

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: macos-latest

    steps:
      # Checkout do código
      - uses: actions/checkout@v4

      # Selecionar versão do Xcode (opcional, caso precise de uma específica)
      - name: Select Xcode
        run: sudo xcode-select -s /Applications/Xcode_16.4.app

      # Build do projeto
      - name: Build
        run: |
          xcodebuild \
            -workspace App.xcworkspace \
            -scheme Movies \
            -sdk iphonesimulator \
            -destination 'platform=iOS Simulator,name=iPhone 15,OS=17.2' \
            clean build

      # Rodar testes
      - name: Run tests
        run: |
          xcodebuild \
            -workspace App.xcworkspace \
            -scheme MoviesTests \
            -sdk iphonesimulator \
            -destination 'platform=iOS Simulator,name=iPhone 15,OS=17.2' \
            test
